### ISSUE TITLE
Multiple instances of d3dshot.create = Impossible

### ISSUE THREAD

**Issue by Arcitec** [SerpentAI/D3DShot#12]
```python
import d3dshot
a = d3dshot.create()
b = d3dshot.create()
```

```
Traceback (most recent call last):
  File "C:\Users\Secret\Downloads\demo.py", line 3, in <module>
    b = d3dshot.create()
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\__init__.py", line 70, in create
    pytorch_gpu_is_available=pytorch_gpu_is_available
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\d3dshot.py", line 24, in __init__
    self.detect_displays()
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\d3dshot.py", line 194, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\display.py", line 119, in discover_displays
    dxgi_adapter=dxgi_adapter
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\display.py", line 40, in __init__
    self.dxgi_output_duplication = self._initialize_dxgi_output_duplication()
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\display.py", line 66, in _initialize_dxgi_output_duplication
    return d3dshot.dll.dxgi.initialize_dxgi_output_duplication(self.dxgi_output, self.d3d_device)
  File "C:\Users\Secret\AppData\Local\Programs\Python\Python37\lib\site-packages\d3dshot\dll\dxgi.py", line 257, in initialize_dxgi_output_duplication
    dxgi_output.DuplicateOutput(d3d_device, ctypes.byref(dxgi_output_duplication))
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```

Would this be solvable by making d3dshot share some memory between all instances of the class? For example, the d3dshot module's namespace can be used for storing a single variable that is used by all files that `import d3dshot`. That way, you could store a single COM connection used by all instances of the class, etc... It may be possible to make multiple instances play nicely together that way...

Personally, I made a wrapper module around d3dshot, which just basically does something like this (mine is class-based, this is just an example):

```python
import d3dshot

ScreenGrabber = d3dshot.create()
```

Then I can `from blah import ScreenGrabber` from any other file and can use `ScreenGrabber.screenshot()` etc, all without getting COM errors, since they all share the exact same connection.

The important thing is to store `d3dshot.create` as a static variable in the module itself (outside any classes). And then ensuring that everything else only interacts with that single connection.

**Comment by nbrochu** [comment]
Apologies for the very late reply. 

I agree that this is an issue. Your suggestion is good and making the D3DShot class act as a singleton would prevent users having to make their own wrapper to share state.

**Comment by nbrochu** [comment]
This is the first issue in line for 0.1.5. 

A Windows process is not allowed to spawn more than 1 Desktop Duplication instance. I can't see any reason not to make the D3DShot class a singleton knowing this. On further `d3dshot.create()` calls we can just returned the stored instance.

**Comment by nbrochu** [comment]
Went the singleton route. Subsequent calls to `create()` will return the existing instance with a warning.

![image](https://user-images.githubusercontent.com/35039/84423126-07d12500-abec-11ea-80e4-96418610eac6.png)

**Comment by nbrochu** [comment]
Documented the behavior in the README

[https://github.com/SerpentAI/D3DShot#singleton](https://github.com/SerpentAI/D3DShot#singleton)

**Comment by Arcitec** [comment]
@nbrochu Great work, looks good to me! Thanks!
