### ISSUE TITLE
COMError with pytorch

### ISSUE THREAD

**Issue by yaodix** [SerpentAI/D3DShot#14]
hi,thanks for your great lib. when i use it in a conda environment installed pytorch_gpu,it doensn't work, error occurs 
`  Traceback (most recent call last):
  File "C:/CenterNet/src/d3d_demo.py", line 10, in <module>
    d = d3dshot.create(capture_output="numpy") #capture_output="numpy"
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\__init__.py", line 70, in create
    pytorch_gpu_is_available=pytorch_gpu_is_available
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\d3dshot.py", line 24, in __init__
    self.detect_displays()
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\d3dshot.py", line 194, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\display.py", line 119, in discover_displays
    dxgi_adapter=dxgi_adapter
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\display.py", line 40, in __init__
    self.dxgi_output_duplication = self._initialize_dxgi_output_duplication()
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\display.py", line 66, in _initialize_dxgi_output_duplication
    return d3dshot.dll.dxgi.initialize_dxgi_output_duplication(self.dxgi_output, self.d3d_device)
  File "C:\Users\yao\Anaconda3\envs\CenterNet\lib\site-packages\d3dshot\dll\dxgi.py", line 257, in initialize_dxgi_output_duplication
    dxgi_output.DuplicateOutput(d3d_device, ctypes.byref(dxgi_output_duplication))
_ctypes.COMError: (-2005270524, 'The specified device interface or feature level is not supported on this system。', (None, None, None, 0, None))`
when I uninstalled pytorch, it can capture frames well,(but first run frame is full of noise).
I wanna use d3dshot and pytorch to make a aimbot ,may help me solve this problems,thank u very much!

**Comment by yaodix** [comment]
by the way,my sys is win10 64bit

**Comment by nbrochu** [comment]
Apologies for the late reply.

If you do have a 64-bit Windows 10, you have the correct DLLs on the system. The next thing that needs to be validated is that you have a 64-bit Python install. Can you confirm this is the case?

The other, rarer, possibility is that your hardware is lacking some of the required capabilities that Direct 3D needs for screen capture. What is your GPU?
