### ISSUE TITLE
Error: Access violation

### ISSUE THREAD

**Issue by coolq1000** [SerpentAI/D3DShot#3]
Hi,

First off, thanks for making this brilliant library =)
I was unable to get it to work properly on my machine however, I'm getting a strange memory error when I run this simple code:
```python
import d3dshot

d = d3dshot.create()
d.screenshot()
```

```
Traceback (most recent call last):
  File "C:/Users/coolq/OneDrive/Projects/Python/main.py", line 4, in <module>
    d = d3dshot.create()
  File "C:\Users\coolq\OneDrive\Projects\Python\venv\lib\site-packages\d3dshot\__init__.py", line 70, in create
    pytorch_gpu_is_available=pytorch_gpu_is_available
  File "C:\Users\coolq\OneDrive\Projects\Python\venv\lib\site-packages\d3dshot\d3dshot.py", line 23, in __init__
    self.detect_displays()
  File "C:\Users\coolq\OneDrive\Projects\Python\venv\lib\site-packages\d3dshot\d3dshot.py", line 192, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Users\coolq\OneDrive\Projects\Python\venv\lib\site-packages\d3dshot\display.py", line 85, in discover_displays
    dxgi_factory = d3dshot.dll.dxgi.initialize_dxgi_factory()
  File "C:\Users\coolq\OneDrive\Projects\Python\venv\lib\site-packages\d3dshot\dll\dxgi.py", line 189, in initialize_dxgi_factory
    create_factory_func(IDXGIFactory1._iid_, ctypes.byref(handle))
OSError: exception: access violation writing 0x4DBAF26F
```

I'm running Windows 10 Pro 64-bit, I have two screens driven by a GTX 1060.

I'm running this with Python 3.6.

Any ideas? 😮

**Comment by nbrochu** [comment]
Is your Python 3.6 also 64-bit? D3DShot uses OS DLLs and using a 64-bit Windows 10 means that 64-bit memory addresses will be thrown around. Those addresses can't be accessed if the bitness of your Python doesn't match that of your OS. It usually doesn't matter to have a bitness mismatch because Python manages memory internally but in the case of D3DShot, it tries to access pointers in memory created by the DLL functions.

I will try to improve the documentation once I understand where people are running into issues.

**Comment by coolq1000** [comment]
No my python installation is 32-bit, it did cross my mind that I might have had the wrong version.

Alright, I switched it and it works perfectly! Thanks for your help =)

**Comment by OzgunKB** [comment]
Same error. Windows 10 x64. GTX 1060. 
Python 64bit.
