### ISSUE TITLE
COMError at create()

### ISSUE THREAD

**Issue by mcagricaliskan** [SerpentAI/D3DShot#34]
```
import time
import d3dshot

screen = d3dshot.create(capture_output="numpy")
```

```
  File "C:\Users\mehmet\AppData\Roaming\Python\Python37\site-packages\d3dshot\display.py", line 69, in _initialize_dxgi_output_duplication
    self.dxgi_output, self.d3d_device
  File "C:\Users\mehmet\AppData\Roaming\Python\Python37\site-packages\d3dshot\dll\dxgi.py", line 284, in initialize_dxgi_output_duplication
    dxgi_output.DuplicateOutput(d3d_device, ctypes.byref(dxgi_output_duplication))
_ctypes.COMError: (-2005270524, 'Belirtilen aygıt arabirimi veya özellik düzeyi bu sistemde desteklenmiyor.', (None, None, None, 0, None))
```
Thats Turkish 'Belirtilen aygıt arabirimi veya özellik düzeyi bu sistemde desteklenmiyor." but in English "The specified device interface or feature level is not supported on this system."

RTX2060, Laptop, Windows 10 version 2004 

I unistalled nvidia driver 452.06 and its work but with drivers it dosent work!

```
import time
import d3dshot
import cv2

screen = d3dshot.create(capture_output="numpy")
print(screen.display)
```
![image](https://user-images.githubusercontent.com/18111855/92284763-6ff18780-ef0b-11ea-9262-0f28872c49b9.png)

**Comment by Pro100rus32** [comment]
I have exactly the same problem! I join.
I can't even see the information about the displays

```
Traceback (most recent call last):
  File "E:\ChatBotAI\AiCharli.py", line 4, in <module>
    screen = d3dshot.create(capture_output="numpy")
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\__init__.py", line 68, in create
    d3dshot = D3DShot(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\d3dshot.py", line 17, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\d3dshot.py", line 37, in __init__
    self.detect_displays()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\d3dshot.py", line 215, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\display.py", line 119, in discover_displays
    display = cls(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\display.py", line 39, in __init__
    self.dxgi_output_duplication = self._initialize_dxgi_output_duplication()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\display.py", line 68, in _initialize_dxgi_output_duplication
    return d3dshot.dll.dxgi.initialize_dxgi_output_duplication(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\dll\dxgi.py", line 284, in initialize_dxgi_output_duplication
    dxgi_output.DuplicateOutput(d3d_device, ctypes.byref(dxgi_output_duplication))
_ctypes.COMError: (-2005270524, 'Указанный интерфейс устройства или уровень компонента не поддерживается в данной системе.', (None, None, None, 0, None))
```

**Comment by Muhammadyusuf96** [comment]
@mcagricaliskan @Pro100rus32 Select the power saving mode on the control panel of the installed video card.

**Comment by xiaochuan-li** [comment]
same error, is there any idea about it?

**Comment by Hellikandra** [comment]
The error code provide by the COM is : DXGI_ERROR_DEVICE_REMOVED.

 on Nvidia : https://www.nvidia.com/en-us/geforce/forums/geforce-experience/14/150018/dxgi-error-device-removed/

Maybe you can found a solution over there.
