### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by Pro100rus32** [SerpentAI/D3DShot#37]
windows 10
screen 1366x768
Notebook (with nvidia 940m)
python 3.8

I tried to run the code (Any) and it doesn't work for me.
```
Traceback (most recent call last):
  File "E:\NEWEXEC2\Hello.py", line 3, in <module>
    d = d3dshot.create(capture_output="numpy")
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\__init__.py", line 68, in create
    d3dshot = D3DShot(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\d3dshot.py", line 17, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\d3dshot.py", line 37, in __init__
    self.detect_displays()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\d3dshot.py", line 215, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\display.py", line 119, in discover_displays
    display = cls(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\display.py", line 39, in __init__
    self.dxgi_output_duplication = self._initialize_dxgi_output_duplication()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\display.py", line 68, in _initialize_dxgi_output_duplication
    return d3dshot.dll.dxgi.initialize_dxgi_output_duplication(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\d3dshot\dll\dxgi.py", line 284, in initialize_dxgi_output_duplication
    dxgi_output.DuplicateOutput(d3d_device, ctypes.byref(dxgi_output_duplication))
_ctypes.COMError: (-2005270524, 'Указанный интерфейс устройства или уровень компонента не поддерживается в данной системе.', (None, None, None, 0, None))
```

**Comment by ghost** [comment]
https://github.com/SerpentAI/D3DShot/wiki/Installation-Note:-Laptops

**Comment by Pro100rus32** [comment]
> https://github.com/SerpentAI/D3DShot/wiki/Installation-Note:-Laptops

```
line 3, in <module>
    d = d3dshot.create()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\d3dshot\__init__.py", line 68, in create
    d3dshot = D3DShot(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\d3dshot\d3dshot.py", line 17, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\d3dshot\d3dshot.py", line 37, in __init__
    self.detect_displays()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\d3dshot\d3dshot.py", line 215, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\d3dshot\display.py", line 93, in discover_displays
    dxgi_factory = d3dshot.dll.dxgi.initialize_dxgi_factory()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\d3dshot\dll\dxgi.py", line 210, in initialize_dxgi_factory
    create_factory_func(IDXGIFactory1._iid_, ctypes.byref(handle))
OSError: exception: access violation writing 0x4DBAF26F

Process returned 1 (0x1)        execution time : 0.250 s
```
