### ISSUE TITLE
pip install d3dshot isn't working

### ISSUE THREAD

**Issue by AdroitBit** [SerpentAI/D3DShot#52]
I follow https://pypi.org/project/d3dshot/

My python version is 3.10

I install Pillow package using `pip install Pillow`
then I run `pip install d3dshot` on Windows PowerShell and get this error :
```
PS C:\Users\Yanothai Chaitawat> pip install d3dshot
Collecting d3dshot
  Using cached D3DShot-0.1.5-py3-none-any.whl (24 kB)
Collecting comtypes<1.2.0,>=1.1.7
  Using cached comtypes-1.1.11-py2.py3-none-any.whl (167 kB)
Collecting pillow<7.2.0,>=7.1.2
  Using cached Pillow-7.1.2.tar.gz (38.9 MB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pillow, since package 'wheel' is not installed.
Installing collected packages: pillow, comtypes, d3dshot
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.1.0
    Uninstalling Pillow-9.1.0:
      Successfully uninstalled Pillow-9.1.0
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yanothai Chaitawat\\AppData\\Local\\Temp\\pip-install-8ciz7jnr\\pillow_a2725d3477104ef19c3fdc565e33e203\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yanothai Chaitawat\\AppData\\Local\\Temp\\pip-install-8ciz7jnr\\pillow_a2725d3477104ef19c3fdc565e33e203\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-record-_hls1_ye\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\Include\pillow'
         cwd: C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-install-8ciz7jnr\pillow_a2725d3477104ef19c3fdc565e33e203\
    Complete output (175 lines):
    C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-install-8ciz7jnr\pillow_a2725d3477104ef19c3fdc565e33e203\setup.py:42: RuntimeWarning: Pillow 7.1.2 does not support Python 3.10 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      warnings.warn(
    running install
    C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.10\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.10\PIL
    running egg_info
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.ci'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-install-8ciz7jnr\pillow_a2725d3477104ef19c3fdc565e33e203\setup.py", line 860, in <module>
        setup(
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 68, in run
        return orig.install.run(self)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\install.py", line 662, in run
        self.run_command('build')
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-install-8ciz7jnr\pillow_a2725d3477104ef19c3fdc565e33e203\setup.py", line 694, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-install-8ciz7jnr\pillow_a2725d3477104ef19c3fdc565e33e203\setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
  Rolling back uninstall of Pillow
  Moving to c:\users\yanothai chaitawat\appdata\local\programs\python\python310\lib\site-packages\pil\
   from C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\Lib\site-packages\~il
  Moving to c:\users\yanothai chaitawat\appdata\local\programs\python\python310\lib\site-packages\pillow-9.1.0.dist-info\
   from C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\Lib\site-packages\~illow-9.1.0.dist-info
ERROR: Command errored out with exit status 1: 'C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yanothai Chaitawat\\AppData\\Local\\Temp\\pip-install-8ciz7jnr\\pillow_a2725d3477104ef19c3fdc565e33e203\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yanothai Chaitawat\\AppData\\Local\\Temp\\pip-install-8ciz7jnr\\pillow_a2725d3477104ef19c3fdc565e33e203\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Yanothai Chaitawat\AppData\Local\Temp\pip-record-_hls1_ye\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\Include\pillow' Check the logs for full command output.
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\Yanothai Chaitawat\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.
```

And during d3dshot even tried to uninstall the Pillow package.
I don't see why this module should do that.

**Comment by Avnsx** [comment]
Same issue on python 3.10.2, windows 10 64 bit

Edit: this will most likely fix: https://github.com/SerpentAI/D3DShot/issues/44#issuecomment-1005867498
